### ISSUE TITLE
64 arm Architecture  Issue

### ISSUE THREAD

**Issue by nadagamal** [RestKit/RestKit#2239]
Hi , 
When I update the architecture to 64 bit these issues appear . So what can I do ? , My deployment target is 7.1 .

Undefined symbols for architecture x86_64:
  "_OBJC_CLASS_$_RKClient", referenced from:
      objc-class-ref in AppDelegate.o
      objc-class-ref in SSRSuggestion.o
  "_OBJC_CLASS_$_RKObjectManager", referenced from:
      objc-class-ref in CinemaDetails-3BD8C6BC69EF1F23.o
      objc-class-ref in AppDelegate.o
      objc-class-ref in HomeScreen.o
      objc-class-ref in MovieDetails.o
      objc-class-ref in CinemaFilter-46E8309ACAC69139.o
      objc-class-ref in FilterView.o
  "_OBJC_CLASS_$_RKObjectMapping", referenced from:
      objc-class-ref in Cinema.o
      objc-class-ref in Movie.o
      objc-class-ref in Filter.o
      objc-class-ref in AppInfoModel.o
  "_OBJC_CLASS_$_RKParserRegistry", referenced from:
      objc-class-ref in SSRSuggestion.o
  "_OBJC_CLASS_$_RKRequestQueue", referenced from:
      objc-class-ref in CinemaDetails-3BD8C6BC69EF1F23.o
      objc-class-ref in AppDelegate.o
      objc-class-ref in MovieDetails.o
  "_OBJC_CLASS_$_RKRequestSerialization", referenced from:
      objc-class-ref in SSRSuggestion.o
  "_RKMIMETypeJSON", referenced from:
      -[SSRSuggestion send_btn_pressed:] in SSRSuggestion.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

Thanks a lot, 
Regards, 
Nada Gamal
